default:
  postgis_host: "localhost" # if using docker swarm, set to service name
  postgis_port: 5432
  postgis_dbname: "operations_db"
  postgis_username: "admin"
  postgis_password: "test" # set to a secret
